### ISSUE TITLE
I can help

### ISSUE THREAD

**Issue by athakral** [Shiqan/FortniteReplayDecompressor#1]
Hi Shiqan,

I would love to help on the fortnite replay reader and decompressor project. 

I have gone through Fredi Machado's video(https://www.youtube.com/watch?v=m2Twu9k5VQQ)

and I also have kind of gone through the CPP code of UnRealEngine

You can always DM me https://twitter.com/1thakral

**Comment by Shiqan** [comment]
Hi athakral,
Of course your help is welcome. You can chat with us on [Discord](https://discord.gg/p5CMqJC).
Or create issues when you see something wrong, or just make a PR 😃 

Cheers,
Shiqan
