### ISSUE TITLE
Visual Studio Version?

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#10]
What Visual Studio version are you guys using?  I currently have VS 2017 but when I open the solution I get errors like "The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.".  I have .net core 3.1 installed.

Sorry, I'm a C++ guy not a C# guy.

**Comment by Kuinox** [comment]
You need to install the the correct .NET SDK.
Visual Studio use the SDK to build your projects.
It's available here: https://dotnet.microsoft.com/download

**Comment by Shiqan** [comment]
2017 doesnt support .net core 3.1, you can "downgrade" to 3.0 if you want. 
Otherwise you can install 2019 16.4.0, which is supporting the new 3.1.

**Comment by stevegee58** [comment]
I upgraded to VS 2019 and the solution opens without errors now.

When I try to build I get 15 errors similar to:
"Error	CS0006	Metadata file 'O:\FortniteReplayDecompressor\src\Unreal.Encryption\bin\Debug\netcoreapp3.1\Unreal.Encryption.dll' could not be found	Unreal.Core	O:\FortniteReplayDecompressor\src\Unreal.Core\CSC"

**Comment by Shiqan** [comment]
The Oodle dll is not included indeed, you can find it in the fortnite installation folder or somewhere on the internet. I'll create some getting started documentation to prevent these kind of questions :)

**Comment by stevegee58** [comment]
Yay, I did it!  So the key starting points are:

- Install Visual Studio 2019 C# (Older VS versions aren't compatible)
- Copy oo2core_5_win64.dll from the Fortnite install folder to FortniteReplayDecompressor/oodle
