### ISSUE TITLE
Newest replay files don't parse

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#12]
Looks like the latest replay files don't parse.  Also the python parser doesn't work either.
I've attached a replay from Feb 23.
[UnsavedReplay-2020.02.23-20.41.43.replay.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/4251031/UnsavedReplay-2020.02.23-20.41.43.replay.zip)

**Comment by Shiqan** [comment]
Thanks for headsup. Hope you dont mind your replay is now included as the season12.replay for eternity :)

**Comment by stevegee58** [comment]
That's OK since it was another Victory Royale! :p
