### ISSUE TITLE
Crashing in Oodle.cs, same replay file

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#13]
The replay file I uploaded in issue #12 is still crashing in Oodle.cs line 23: "System.OverflowException: 'Arithmetic operation resulted in an overflow.'"
I think one of the size variables like uncompressedSize has overflowed signed 32 bits.  These maybe should all be unsigned long instead of int.
I've uploaded a debugger screenshot.
![Capture](https://user-images.githubusercontent.com/1463702/75362863-54843080-5887-11ea-8eca-6869b4c51371.PNG)

**Comment by Shiqan** [comment]
Works on the current master branch, you probably missed a commit I did. But the nice thing about forking, you can actually pull in the upstream commits! You should google it to be sure, but something like this from the top of my head:
`git fetch upstream` and `git merge upstream/master`.
That should resolve your issues :)

**Comment by stevegee58** [comment]
Oops, you're right.  My copy of your repo got borked so I didn't get your latest updates.
I've been using SVN for years and only just started using git in my day job.
