### ISSUE TITLE
Eliminated and Eliminator are always Guids (no real names)

### ISSUE THREAD

**Issue by EAbychkov** [Shiqan/FortniteReplayDecompressor#14]
I just started to use your lib and find out that it's impossible to get real players' names from it. 
Is this a bug or it's the correct behavior? If so, how can I get real players' names?
Please find attached JSON file 
I got it from the execution of:
`reader.ReadReplay(filePath)`
[Untitled-1.txt](https://github.com/Shiqan/FortniteReplayDecompressor/files/4364847/Untitled-1.txt)

**Comment by Shiqan** [comment]
Hi @EAbychkov , playernames are encrypted in the replay files and we only get the EPIC Id for a player. You'll have to lookup the playernames yourself,

**Comment by EAbychkov** [comment]
> Hi @EAbychkov , playernames are encrypted in the replay files and we only get the EPIC Id for a player. You'll have to lookup the playernames yourself,

Sorry for a probably stupid question, but how can I lookup the playernames yourself? 
I have a list of GUIDs there and how can I match them to real players names to get to know the score?

**Comment by Shiqan** [comment]
You can make API calls to get the playername from the EPIC id (guid). Eg the interal fortnite api but there are several others as well such as fortnitetracker

**Comment by EAbychkov** [comment]
Ok, great, thanks!

**Comment by EAbychkov** [comment]
hm... it looks like it's impossible to convert EpicId to PlayerName because official public Fortnite API is not available, fortnitetracker doesn't provide such an API call and fortniteapi.com site doesn't work at all.
Does this mean that it's impossible to get any useful information from FortniteReplayDecompressor for now?

**Comment by Kuinox** [comment]
Fortnite API is undocumented but you can query it, some librairies already does this, for exemple this one: https://github.com/qlaffont/fortnite-api/   
A lot of people use epic guid today so we know it's possible...
