### ISSUE TITLE
Nuget package is missing dependencies

### ISSUE THREAD

**Issue by benwurth** [Shiqan/FortniteReplayDecompressor#15]
When I tried using the FortniteReplayReader Nuget package in a simple command line application, I got a *runtime* error telling me it couldn't find the assembly for Unreal.Encryption version 1.0.0.

Hopefully this is just a build configuration issue that can be fixed easily, or at the very least, turned into a *compile time* error.

**Comment by Shiqan** [comment]
Hi @benwurth, I was aware but was hoping nobody noticed just yet :)
Was struggling with `dotnet pack` and project references, in the end I published all as seperate Nuget packages 🤷‍♂ 
Anyway, should be fixed now (>= 1.0.3)
Thanks for letting me know!
