### ISSUE TITLE
Can't set breakpoints in FortniteReplayBuilder or FortniteReplayReader

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#16]
I did a pull today for the first time in a couple of months.
I can run debug and set breakpoints in Program.cs but not in the FortniteReplayReader cs files.  It's acting like FortniteReplayReader is being built release/optimized but the settings show debug.
Maybe something changed in the csproj or sln files?

**Comment by Shiqan** [comment]
I changed to nuget references and no longer package references (because dotnet pack is stupid).
You can either use the nuget switcher, or "just" change the reference to a project reference.

**Comment by stevegee58** [comment]
Ah OK.  I'm a Linux C++ guy so this C# stuff is a little weird.  Where are the references stored and how do I change them?

**Comment by Shiqan** [comment]
In Visual Studio, you can remove the Nuget package references from each project and then add a project reference:
- Open a project -> Dependencies -> Packages -> remove
- Right click dependencies -> Add Reference -> Select Projects on the left hand side of the popup, and then select the project reference for the Nuget package you just removed.

**Comment by stevegee58** [comment]
It worked! Thanks!
I tried nuget switcher but threw an error.  I'm using Visual Studio 2019.
