### ISSUE TITLE
How to track some elements of replays without massively increasing processing time?

### ISSUE THREAD

**Issue by Lucas7yoshi** [Shiqan/FortniteReplayDecompressor#25]
Hey, i run a project that analyzes large amounts of replays using the replaydecompressor, and i currently use the "Minimal" searching for its speed. I was however wondering if it would be possible to add a few elements to minimal.

i expect i'd need to fork it, and i did attempt to do it before but i failed to get it to compile and got stuck.

Things i want to parse are the MapData -> Safezones & Llamas.

Apologies if this is an improper use of the issues, but i've seen repo's use it for support kind of before so im giving it a try.

**Comment by Shiqan** [comment]
Hi, obviously you can fork it (or just download the source code) and modify the parse levels for those 2 classes (eg https://github.com/Shiqan/FortniteReplayDecompressor/blob/4bf5da2d17adc9d0f94fa1752bfa28a0d556f3df/src/FortniteReplayReader/Models/NetFieldExports/SupplyDropLlama.cs#L8).
Unfortunately I dont think there is an easier way.

**Comment by Lucas7yoshi** [comment]
I could have sworn that I attempted to do basically just that previously with no luck but I'll give it another shot when I have the time. thank you for the response

**Comment by Lucas7yoshi** [comment]
Unfortunately made little progress, im getting everything but the part i want: the location coordinates.

Not sure what to do next? https://l7y.ca/files/sx/2021-01-28_00-02-36_454x271_H3Y0.png

**Comment by Shiqan** [comment]
Can you share the replay? If I change those two levels I do get all the values. I dont have any recent replays though so maybe something changed somewhere...
