### ISSUE TITLE
Chapter 2 Season 7 replays hang

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#28]
The replay files in season 7 cause the parser to hang.  No errors are printed.

**Comment by BenTheWood** [comment]
Had the same issue so I looked into it and found the problem. 

The _logger variable on line 1304 of Unreal.Core/ReplayReader.cs is missing its null check. After adding the check the replays seems to be read correctly.

**Comment by stevegee58** [comment]
Interesting.  It looks like the _logger member variable is being correctly filled in by the constructor from ConsoleReader/Program.cs where it's newed.  Maybe the code paths that call the logger weren't even being visited before.

I'll check further when I get home.

**Comment by Shiqan** [comment]
I think this commit is needed: https://github.com/Shiqan/FortniteReplayDecompressor/commit/5d01ae56fbac998492c38679d7c12591f1eb4b03

You should check out SL-x-TnT's fork, it contains this fix and is much (much) faster.

**Comment by stevegee58** [comment]
I switched to the feature/net5 branch and rebuilt and it works now.
