### ISSUE TITLE
HttpNetworkReplay

### ISSUE THREAD

**Issue by Skamiplan** [Shiqan/FortniteReplayDecompressor#37]
Hey, awesome project digging through it taught me a few new tricks.
I was wondering if it was possible to perhaps add support for [HttpNetworkReplayStreaming](https://github.com/EpicGames/UnrealEngine/blob/70bc980c6361d9a7d23f6d23ffe322a2d6ef16fb/Engine/Source/Runtime/NetworkReplayStreaming/HttpNetworkReplayStreaming/Private/HttpNetworkReplayStreaming.cpp), I've been trying to get it working for a while now myself, created my own [replay server](https://docs.unrealengine.com/4.27/en-US/TestingAndOptimization/ReplaySystem/Streamers/HTTPRESTAPI/) from which I can serve the streaming chunks to help analyze what's exactly going on in the files. 
However the only thing that I was able to get working was the replay.header.
![image](https://user-images.githubusercontent.com/6513758/147822750-a8e544c8-d7e8-49d7-a992-892bb8a3a2a4.png)

The way the engine seems to handle HTTP Replays is by making the following requests

 - POST https://replays.newworldinteractive.com/client_14/replay/6adcf1a7-ac78-4aa2-83bb-724fb1a151ba/startDownloading?user=76561197991255957
	 - This contains the state of the replay, either Final or Live.
	 - The number of chunks for this replay.
	 - The time in MS for the duration of this replay.
	 - The current viewerId.
		 - `{"state":"Final","numChunks":161,"time":1581490,"viewerId":"1f87975e-a3c7-4e2a-a70b-a12baa311143"}`
 - GET https://replays.newworldinteractive.com/client_14/replay/6adcf1a7-ac78-4aa2-83bb-724fb1a151ba/file/replay.header
	 - This contains the basic game information in binary response, what map what build etc. Just like the Fortnite replay.header.
 - GET https://replays.newworldinteractive.com/client_14/replay/6adcf1a7-ac78-4aa2-83bb-724fb1a151ba/file/stream.0
	 - stream.{chunkNumber} being which chunk.
	 - This contains the first chunk of the replay information in the binary response.
	 - It returns HTTP Headers about the state of this chunk.
		 - HTTP Headers
			 - NumChunks (same as startDownloading (as long as it isn't a Live Replay))
			 - Time (same as startDownloading (as long as it isn't a Live Replay))
			 - State (same as startDownloading (as long as it isn't a Live Replay))
			 - MTime1 (the start in MS of where this chunk belongs in the Replay)
			 - MTime2 (the end in MS of where this chunk belongs in the Replay)

Please let me know if I can in anyway help or assist you.

The files do not appear to be compressed nor encrypted.

**Comment by Shiqan** [comment]
Hi, interesting stuff! 
Had a quick look, and I think it is quite simple because at first glance it seems like the /file/replay.header can be parsed by the method `ReadReplayHeader` (as you already showed) and the /file/stream.{index} responses can be parsed by the method `ReadReplayData`. Not sure how checkpoints come into this, but I think that is a completely [different request](https://github.com/EpicGames/UnrealEngine/blob/70bc980c6361d9a7d23f6d23ffe322a2d6ef16fb/Engine/Source/Runtime/NetworkReplayStreaming/HttpNetworkReplayStreaming/Private/HttpNetworkReplayStreaming.cpp#L994)

We can add a `HttpReplayReader` or something that takes care of the downloading of the chunks? I should have some time tomorrow to play with that a bit. Obviously, if you want you can also create a (draft) PR with an implementation :)

**Comment by Skamiplan** [comment]
Hey, thanks for the reply.

> Not sure how checkpoints come into this, but I think that is a completely [different request](https://github.com/EpicGames/UnrealEngine/blob/70bc980c6361d9a7d23f6d23ffe322a2d6ef16fb/Engine/Source/Runtime/NetworkReplayStreaming/HttpNetworkReplayStreaming/Private/HttpNetworkReplayStreaming.cpp#L994)

I believe this might be the URL you are referring to https://replays.newworldinteractive.com/client_14/replay/6adcf1a7-ac78-4aa2-83bb-724fb1a151ba/event?group=checkpoint

It gets called a few between the `startDownloading` and first chunk requests `stream.0`.
![image](https://user-images.githubusercontent.com/6513758/147854622-6822935c-a5f1-404f-85e9-5345fed3783d.png)


It returns JSON with timestamps.
I've been able to get replays working in the game itself without my own HTTP Replay server returning this request.
So I'm not sure it it contains anything critical.

As for the `ReadReplayData` method, I haven't been able to get this working correctly cause the magic bytes (besides for the `ReadReplayHeader` seem to be different each for each stream.
Every stream.0 chunk seems to start with `00 00 00 00 **86 0A 89 3C 6B** 08 02 02 1C 00 00 00` where the bytes between the `**` are different every time.

If you think it would help I can share the source code for the custom HTTP Replay server and a bunch of replay files.

**Comment by Shiqan** [comment]
Looking at json response for the event endpoint, it seems to be just the [event data](https://fortnitereplaydecompressor.readthedocs.io/en/latest/overview/) that is used to add markers on a timeline inside the replay viewer. For Fortnite (the local replay streamer) they're included in the replay itself, but for the http streamer there is simply an endpoint to get all events :)
