### ISSUE TITLE
PlayerData no longer includes EpicId or PlayerId

### ISSUE THREAD

**Issue by brbarnett** [Shiqan/FortniteReplayDecompressor#47]
This is probably a client update that has changed the replay file format, but I am now receiving `null` values in `PlayerData` on both `EpicId` and `PlayerId`. Client version is `26.00`. Example item:

```
            {
                "epicId": null,
                "id": null,
                "isBot": false,
                "kills": null,
                "placement": 4,
                "platform": "WIN",
                "playerId": null,
                "playerName": "El_Jenio19",
                "teamIndex": 3,
                "teamKills": null
            },
[UnsavedReplay-2023.09.08-11.13.31.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/12561836/UnsavedReplay-2023.09.08-11.13.31.zip)

```

We use the Epic ID from `playerId` to perform some automation and account linking on our end.

Sample replay file attached

**Comment by brbarnett** [comment]
Also, this bleeds through into `teamData`. Here's an example from there:
```
            {
                "teamIndex": 3,
                "playerIds": [
                    null
                ],
                "playerNames": [
                    null
                ],
                "partyOwnerId": null,
                "placement": 4,
                "teamKills": null
            },
```

**Comment by brbarnett** [comment]
Thank you @Shiqan! Can't believe how quickly you turned this around. Nicely done! 🎉

**Comment by Shiqan** [comment]
Would love to take the credits, but actually badmate (developer of  [yunite](https://yunite.xyz/)) warned us in the Discord server on the release of 26.0. I just missed it 😇
