### ISSUE TITLE
bitstring.exceptions.ReadError: Reading off the end of the data.

### ISSUE THREAD

**Issue by BobJr23** [Shiqan/FortniteReplayDecompressor#51]
Why am I getting this error when using Reader(f.read())

**Comment by BobJr23** [comment]
@Shiqan Thanks for your response, is there any way I could check which parts of the replay header changed?

**Comment by Shiqan** [comment]
This method https://github.com/Shiqan/FortniteReplayDecompressor/blob/c322d58dd0424f6bdbd33bf11812554a2a9f04f7/src/Unreal.Core/ReplayReader.cs#L387
should be in sync with its Python variant: https://github.com/Shiqan/fortnite-replay-reader/blob/5efb522704621c66ace840c9968777f682ae2adb/ray/reader.py#L158

The same problem(s) might apply to the rest of the Python code as well, for instance, parsing eliminations.
