### ISSUE TITLE
Replay Stats not loading for custom maps

### ISSUE THREAD

**Issue by cormac-doyle** [Shiqan/FortniteReplayDecompressor#53]
When trying to access Stats class in replay files on custom maps I get null pointer exception error:
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by cormac-doyle** [comment]
Example file:
[custom.replay.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/14516463/custom.replay.zip)

**Comment by Shiqan** [comment]
`Stats` is an event (`AthenaMatchStats`) from Fornite replays. so not something custom we've build.
If it is null, it means it wasnt an event in the replay. So I guess Fortnite will not send this event for custom game mode.
