### ISSUE TITLE
Placement information is sometimes not available

### ISSUE THREAD

**Issue by BeereMgM** [Shiqan/FortniteReplayDecompressor#56]
Hello.
Sometimes I dont get information about a teams placement. Is there any fix? 
![image](https://github.com/Shiqan/FortniteReplayDecompressor/assets/80534799/52aad88f-c3b8-4cc6-ae53-a3f153a5c9af)

Thanks!

**Comment by BeereMgM** [comment]
(addition)
The placements arent available for the places 1-14

**Comment by Shiqan** [comment]
If you leave before the game is finished, we obviously dont know the placements of the remaining players at that point.
If that isnt the case, please share the replay and I can have a look to see where it goes wrong.

Placement is coming from `FortPlayerStateAthena` if you want to debug it yourself:
https://github.com/Shiqan/FortniteReplayDecompressor/blob/master/src/FortniteReplayReader/Models/NetFieldExports/FortPlayerState.cs#L119-L120

**Comment by BeereMgM** [comment]
Hey again.
Thanks for your response!
I got first place in this replay, so I was the last one alive.
Here is the replay file: [Uploading UnsavedReplay-2024.03.23-15.18.05.zip…]()

**Comment by BeereMgM** [comment]
Hey again.
Thanks for your response!
I got first place in this replay, so I was the last one alive.
Here is the replay file: 
[UnsavedReplay-2024.03.23-15.18.05.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/14806470/UnsavedReplay-2024.03.23-15.18.05.zip)

**Comment by Shiqan** [comment]
Had a quick look, and they are indeed not there🤔 
Cant see anything going wrong either, but something could be failing silently...
Would have to see what changed in the recent UE builds.

**Comment by BeereMgM** [comment]
Would be amazing if you could check this! 
Please let me know if you got more informations!

Have a great easter festival!

**Comment by Shiqan** [comment]
He, if you play this play in replay in Fortnite, does it include the end?
It almost feels like it is straight up missing the last chunk(s) of the replay.

If I log all events for your user (for `FortPlayerStateAthena`, coming in on channel 213 if you want to have a look yourself) I barely get anything after the initial values. Only that you were `bInAircraft`,  `bThankedBusDriver` (important 👍) and `bHasEverSkydivedFromBus`, followed by `bHasEverSkydivedFromBusAndLanded` and then the 2 kills you had early on (updated on `TeamKillScore` and `KillScore`). After that, nothing but `CompressedPing` events until the very end...

**Comment by BeereMgM** [comment]
Thank you for taking the time to help me!
I'm gonna try another replay, where I got first place to see, if its maybe corrupted!
