### ISSUE TITLE
How to use PlayerPawnAI.cs in the project ?

### ISSUE THREAD

**Issue by d3hydr8** [Shiqan/FortniteReplayDecompressor#64]
Thanks for this awesome project. My question is how to use different classes under PlayerPawnAI.cs and where to invoke it.

**Comment by Shiqan** [comment]
Not sure if the `PlayerPawnAI` exports that are defined still exist in the current version of the game 😄 
But in general, if you have a `INetFieldExportGroup` you want to do something with, you need to add it to here: https://github.com/Shiqan/FortniteReplayDecompressor/blob/30d7bb5b9daee5b6d3c67b4a5693d9c0cdb4a83e/src/FortniteReplayReader/FortniteReplayReader.cs#L100

Obviously, you can add more export groups if they dont exist yet.

**Comment by d3hydr8** [comment]
Thanks a lot for helping out.
